#! /usr/bin/python

import random
import string


def word():
    return random.choice(['dogs', 'people', 'shoes', random.choice(['other ', '']) +'tumblr users', 'smart people', 'disney movies', 'super bowl snacks', 'gifts', 'demonstrators', 'books', 'valentines', 'touchdowns', 'puppies', 'actors', 'actresses', 'cars', 'celebrities', 'little kids', 'disney princesses', 'villains', 'classic movies', 'TV shows'])

def believe():
    return 

def punc():
    return random.choice(['.', '!', ''])

def reasons():
    s = str(num) + ' reasons why'
    s += ' ' + word() + ' '
    s += 'are ' + random.choice(['annoying', 'horrible', 'awesome', 'insane', 'superlative', 'funny', 'wrong', 'right', 'the worst', 'the best'])
    s += punc()
    return s

def humanity():
    return 'These ' + str(num) + ' ' + word() + ' will restore your faith in humanity' + punc()

def tears():
    return 'These ' + str(num) + ' ' + word() + ' will ' + random.choice(['make you cry', 'bring you to tears']) + punc() 

def quiz():
    return "QUIZ! Which one of these " + str(num) + " " + word() + " describes " + random.choice(['you', 'your friends', 'your social life', 'your family', 'your parents', 'your music taste']) + '?'

def mostAbout():
    return 'The ' +str(num) +random.choice([random.choice([' best',' worst']), random.choice([' most annoying', ' most horrible', ' most awesome', ' most insane', ' funniest', ' wrongest', ' rightest', ' best'])]) + ' things about ' +word()

d = {1:reasons, 2:humanity, 3:tears, 4:quiz, 5:mostAbout}

num = random.randint(2,60)
pick = random.randint(1,len(d.keys()))
final = ''
final =  d[pick]()
final = string.capwords(final)
if pick != 4 and pick != 3:
    final += random.choice([' (You Won\'t Believe Number ' + str(random.randint(1, num-1)) + '!)'])
print final
